/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_su_androidsample_basicjni_BasicJni */

#ifndef _Included_com_su_androidsample_basicjni_BasicJni
#define _Included_com_su_androidsample_basicjni_BasicJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_su_androidsample_basicjni_BasicJni
 * Method:    generateBooks
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_su_androidsample_basicjni_BasicJni_generateBooks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
